@minimarket_project_backend_HostAddress = http://localhost:5176

GET {{minimarket_project_backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{minimarket_project_backend_HostAddress}}/brands
Accept: application/json
Content-Type: application/json
{
  "Name": "",
  "FileImage": "",
  "Status": false
}